/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 18-Mar-2025 1:15:17 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS admin CASCADE
;

DROP TABLE IF EXISTS camion CASCADE
;

DROP TABLE IF EXISTS chauffeur CASCADE
;

DROP TABLE IF EXISTS citoyen CASCADE
;

DROP TABLE IF EXISTS notification CASCADE
;

DROP TABLE IF EXISTS plainte CASCADE
;

/* Create Tables */

CREATE TABLE admin
(
	id_admin integer NOT NULL,
	username_admin varchar(50) NULL,
	password_admin varchar(50) NULL
)
;

CREATE TABLE camion
(
	id_camion integer NOT NULL,
	status varchar(50) NULL,
	id_chauffeur integer NULL
)
;

CREATE TABLE chauffeur
(
	id_chauffeur integer NOT NULL,
	username_ch varchar(50) NULL,
	password_ch varchar(50) NULL,
	latitude real NULL,
	longitude real NULL,
	id_plainte integer NULL
)
;

CREATE TABLE citoyen
(
	id_citoyen integer NOT NULL,
	name_cit varchar(50) NULL,
	username_cit varchar(50) NULL,
	password varchar(50) NULL,
	id_plainte integer NULL
)
;

CREATE TABLE notification
(
	id_notif integer NOT NULL,
	msg varchar(50) NULL,
	time timestamp without time zone NULL,
	id_chauffeur integer NULL,
	id_admin integer NULL
)
;

CREATE TABLE plainte
(
	id_plainte integer NOT NULL,
	description varchar(50) NULL,
	status_p varchar(50) NULL,
	time timestamp without time zone NULL,
	lat real NULL,
	long real NULL,
	id_citoyen integer NULL,
	id_admin integer NULL,
	id_chauffeur integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE admin ADD CONSTRAINT "PK_admin"
	PRIMARY KEY (id_admin)
;

ALTER TABLE camion ADD CONSTRAINT "PK_camion"
	PRIMARY KEY (id_camion)
;

CREATE INDEX "IXFK_camion_chauffeur" ON camion (id_chauffeur ASC)
;

ALTER TABLE chauffeur ADD CONSTRAINT "PK_chauffeur"
	PRIMARY KEY (id_chauffeur)
;

ALTER TABLE citoyen ADD CONSTRAINT "PK_citoyen"
	PRIMARY KEY (id_citoyen)
;

ALTER TABLE notification ADD CONSTRAINT "PK_notification"
	PRIMARY KEY (id_notif)
;

CREATE INDEX "IXFK_notification_admin" ON notification (id_admin ASC)
;

CREATE INDEX "IXFK_notification_chauffeur" ON notification (id_chauffeur ASC)
;

ALTER TABLE plainte ADD CONSTRAINT "PK_plainte"
	PRIMARY KEY (id_plainte)
;

CREATE INDEX "IXFK_plainte_admin" ON plainte (id_admin ASC)
;

CREATE INDEX "IXFK_plainte_chauffeur" ON plainte (id_chauffeur ASC)
;

CREATE INDEX "IXFK_plainte_citoyen" ON plainte (id_citoyen ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE camion ADD CONSTRAINT "FK_camion_chauffeur"
	FOREIGN KEY (id_chauffeur) REFERENCES chauffeur (id_chauffeur) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE notification ADD CONSTRAINT "FK_notification_admin"
	FOREIGN KEY (id_admin) REFERENCES admin (id_admin) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE notification ADD CONSTRAINT "FK_notification_chauffeur"
	FOREIGN KEY (id_chauffeur) REFERENCES chauffeur (id_chauffeur) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE plainte ADD CONSTRAINT "FK_plainte_admin"
	FOREIGN KEY (id_admin) REFERENCES admin (id_admin) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE plainte ADD CONSTRAINT "FK_plainte_chauffeur"
	FOREIGN KEY (id_chauffeur) REFERENCES chauffeur (id_chauffeur) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE plainte ADD CONSTRAINT "FK_plainte_citoyen"
	FOREIGN KEY (id_citoyen) REFERENCES citoyen (id_citoyen) ON DELETE No Action ON UPDATE No Action
;
